### ISSUE TITLE
Unlabeled gauge bar appearing when playing summoner

### ISSUE THREAD

**Issue by Lumi-sg** [0ceal0t/JobBars#123]
Here's what it looks like if this helps
![unknown](https://user-images.githubusercontent.com/12517973/147193865-7e63d412-1b10-464a-82e6-9104c5bf6141.png)

It only appears while  playing summoner.

It cannot be moved, enabled/disabled etc

Let me know if you need anything else  from me.

**Comment by 0ceal0t** [comment]
Sorry for the late response, the holidays have been really busy for me. Can you confirm if this is still an issue? If it is, can you try wiping your config by deleting `JobBars.json` in your `%Appdata%/XIVLauncher/pluginConfigs` folder (**MAKE SURE YOU SAVE A BACKUP FIRST**)

**Comment by 0ceal0t** [comment]
ah, I think I found the issue actually. You can still test to see if wiping your config fixes the issue if you want, but it should be fixed soon

**Comment by Lumi92** [comment]
Hey sorry I didn't get back to you!

I was about to mention that the new update didn't fix the issue, however in doing some messing around myself realized that in fact my own stupidity was the problem.

I use zeffui's overlay via ACT to display raid buffs/mitigations because I've been too lazy to setup jobbar's implementation. However I have everything else in zeffui disabled as for the most part jobbars has replaced the functionality.

It seems that a setting for "stacks" which only seemed to apply to SMN was still enabled and was the cause of the seemingly non behaving gauge pictured.

I  got fooled because I assumed I had configured zeffui  correctly as well as the fact that the gauge looks identical to jobbars.

I feel like an asshole for wasting your time! Sorry about that...I really am.

-Lumi
